####################### Basic Info #######################

player:
  name:  # Username
  money: 0  # Player Balance

  level: 0  # Overall player level
  xp: 0

  hp: 100
  hunger: 100  # Maximum Hunger
  mp: 0  # Magic Points

  monsters_defeated: 0  # For use with Quest Hall
  stronghold_defeats: 0  # For use with Quest Hall
  
####################### Status Effects #######################

  status_effects:
    # Negative Effects
    nausea:
      active: False
      damage: 5  # Damage dealt per round
    
    poison:
      active: False
      damage: 10  # Damage dealt per round
    
    necromancy:
      active: False
      damage: 30  # Damage dealt per round
    
    # Positive Effects
    rehydration:
      active: False
      newhp: 5  # Damage dealt per round

    healing:
      active: False
      newhp: 10  # Damage dealt per round
    
    resurrection:
      active: False
      newhp: 30  # Damage dealt per round

####################### Equipment #######################

  armor:
    helmet:
      name: Wooden # Name
      type: Basic  # Basic (wood), Normal, Legendary
      resistance: 5  # How much damage is mitigated per round
      durability: 100  # Maximum wear the armor can take
      wear: 0  # How much wear the armor has
      broken: False  # Whether the armor can be used due to wear

    chestplate:
      name: Wooden # Name
      type: Basic  # Basic (wood), Normal, Legendary
      resistance: 5  # How much damage is mitigated per round
      durability: 100  # Maximum wear the armor can take
      wear: 0  # How much wear the armor has
      broken: False  # Whether the armor can be used due to wear

    leggings:
      name: Wooden # Name
      type: Basic  # Basic (wood), Normal, Legendary
      resistance: 5  # How much damage is mitigated per round
      durability: 100  # Maximum wear the armor can take
      wear: 0  # How much wear the armor has
      broken: False  # Whether the armor can be used due to wear

    boots:
      name: Wooden # Name
      type: Basic  # Basic (wood), Normal, Legendary
      resistance: 5  # How much damage is mitigated per round
      durability: 100  # Maximum wear the armor can take
      wear: 0  # How much wear the armor has
      broken: False  # Whether the armor can be used due to wear
  
  weapon:
    name: Bronze
    type: Basic  # Basic (bronze), Normal, Legendary
    sharpness: 30  # Maximum damage that can be dealt each round
    durability: 100  # Maximum wear the weapon can take
    wear: 0  # How much wear the weapon has
    broken: False  # Whether the weapon can be used due to wear

####################### Inventory #######################

  inventory:
    # Skill Plot Items
    supplies:
      bait:  # Fishing
        quantity: 0

      uncooked-fish:  # Fishing
        quantity: 0

      wood:  # Woodcutting
        quantity: 0

      ore:  # Mining
        quantity: 0

      ingots:  # Smithing
        quantity: 0

    food:
      # Includes quantity and hunger as attributes
      cooked-fish: # Cooked in skill plot
        quantity: 0
        hunger: 10  # How much hunger is restored per item consumed

      rations:
        quantity: 0
        hunger: 30  # How much hunger is restored per item consumed

      steak:
        quantity: 0
        hunger: 50  # How much hunger is restored per item consumed

    drops:
      fur:
        quantity: 0
      
      horns:
        quantity: 0
      
      crystal:
        quantity: 0
      
      orbs:
        quantity: 0

####################### Skill Plots #######################

  skills:
    woodcutting:
      level: 0
      xp: 0

    fishing:  # Requires Bait
      level: 0
      xp: 0

    mining:
      level: 0
      xp: 0

    smithing:  # Requires Ore
      level: 0
      xp: 0

    thieving:
      level: 0
      xp: 0
  
####################### Quests #######################

  quests:
    
    monsters: # Number of monsters defeated
      one-hundred:
        completed: False

      two-hundred:
        completed: False
    
    levels: # Reached level #
      ten:
        completed: False

      thirty:
        completed: False
      
      fifty:
        completed: False
    
    stronghold: # Whether the stronghold been defeated a certain number of times
      defeated-one:
        completed: False
      
      defeated-five:
        completed: False


####################### Bank #######################

  bank:
    one:
      empty: True
      money: 0
      limit: 1000000  # $1M

    two:
      empty: True
      money: 0
      limit: 1000000  # $1m

    three:
      empty: True
      money: 0
      limit: 1000000  # $1m

    four:
      empty: True
      money: 0
      limit: 1000000  # $1m

    five:
      empty: True
      money: 0
      limit: 1000000  # $1m

####################### Settings #######################

  settings:
    password:
