####################### Basic Info #######################

player:
  name:
  money: 0

  level: 0
  xp: 0

  hp: 100
  hunger: 100
  mp: 0

  monsters_defeated: 0
  stronghold_defeats: 0
  
####################### Status Effects #######################

  status_effects:
    # Negative Effects
    nausea:
      active: False
      damage: 5
    
    poison:
      active: False
      damage: 10
    
    necromancy:
      active: False
      damage: 30
    
    # Positive Effects
    rehydration:
      active: False
      newhp: 5

    healing:
      active: False
      newhp: 10
    
    resurrection:
      active: False
      newhp: 30

####################### Equipment #######################

  armor:
    helmet: 
      type: Wooden
      resistance: 5
      damage: 0

    chestplate:
      type: Wooden
      resistance: 5
      damage: 0

    leggings:
      type: Wooden
      resistance: 5
      damage: 0

    boots:
      type: Wooden
      resistance: 5
      damage: 0
  
  weapon:
    type: Bronze
    range: 0
    sharpness: 30
    damage: 0

####################### Inventory #######################

  inventory:
    # Skill Plot Items
    supplies:
      bait:
        quantity: 0

      wood:
        quantity: 0

      ore:
        quantity: 0

      ingots:
        quantity: 0

      uncooked-fish:
        quantity: 0

    food:
      # Includes quantity and hunger as attributes
      cooked-fish: # Cooked in skill plot
        quantity: 0
        hunger: 10

      rations:
        quantity: 0
        hunger: 30

      steak:
        quantity: 0
        hunger: 50

    drops:
      fur:
        quantity: 0
      
      horns:
        quantity: 0
      
      crystal:
        quantity: 0
      
      orbs:
        quantity: 0

####################### Skill Plots #######################

  skills:
    woodcutting:
      level: 0
      xp: 0

    fishing:
      level: 0
      xp: 0

    mining:
      level: 0
      xp: 0

    smithing:
      level: 0
      xp: 0

    thieving:
      level: 0
      xp: 0
  
####################### Quests #######################

  quests:
    
    monsters: # Number of monsters defeated
      one-hundred:
        completed: False

      two-hundred:
        completed: False
    
    levels: # Reached level #
      ten:
        completed: False

      thirty:
        completed: False
      
      fifty:
        completed: False
    
    stronghold: # Whether the stronghold been defeated a certain number of times
      defeated-one:
        completed: False
      
      defeated-five:
        completed: False


####################### Bank #######################

  bank:
    one:
      empty: True
      money: 0
      limit: 1000000

    two:
      empty: True
      money: 0
      limit: 1000000

    three:
      empty: True
      money: 0
      limit: 1000000

    four:
      empty: True
      money: 0
      limit: 1000000

    five:
      empty: True
      money: 0
      limit: 1000000

####################### Settings #######################

  settings:
    password:
